from ecommerce_integrations.shopify.order import sync_sales_order


payload = {
    "admin_graphql_api_id": "gid://shopify/Order/11755494146422",
    "app_id": 1354745,
    "billing_address": {
        "country": "Switzerland",
        "country_code": "CH",
        "province": None,
        "province_code": None,
    },
    "browser_ip": "119.73.96.27",
    "buyer_accepts_marketing": False,
    "cancel_reason": None,
    "cancelled_at": None,
    "cart_token": None,
    "checkout_id": 65267918373238,
    "checkout_token": "471cc3e437c6fe6e8007e07e8f659d9e",
    "client_details": {
        "accept_language": None,
        "browser_height": None,
        "browser_ip": "119.73.96.27",
        "browser_width": None,
        "session_hash": None,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
    },
    "closed_at": None,
    "confirmation_number": "5EDEER5XD",
    "confirmed": True,
    "created_at": "2025-05-23T12:22:20+02:00",
    "currency": "CHF",
    "current_shipping_price_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "current_subtotal_price": "111.00",
    "current_subtotal_price_set": {
        "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
        "shop_money": {"amount": "111.00", "currency_code": "CHF"},
    },
    "current_total_additional_fees_set": None,
    "current_total_discounts": "0.00",
    "current_total_discounts_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "current_total_duties_set": None,
    "current_total_price": "111.00",
    "current_total_price_set": {
        "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
        "shop_money": {"amount": "111.00", "currency_code": "CHF"},
    },
    "current_total_tax": "8.32",
    "current_total_tax_set": {
        "presentment_money": {"amount": "8.32", "currency_code": "CHF"},
        "shop_money": {"amount": "8.32", "currency_code": "CHF"},
    },
    "customer": {
        "admin_graphql_api_id": "gid://shopify/Customer/23366289064310",
        "created_at": "2025-05-23T12:21:09+02:00",
        "currency": "CHF",
        "default_address": {
            "company": "England",
            "country": "Switzerland",
            "country_code": "CH",
            "country_name": "Switzerland",
            "customer_id": 23366289064310,
            "default": True,
            "id": 34763750900086,
            "province": "",
            "province_code": None,
        },
        "id": 23366289064310,
        "multipass_identifier": None,
        "note": "",
        "state": "disabled",
        "tax_exempt": False,
        "tax_exemptions": [],
        "updated_at": "2025-05-23T12:22:21+02:00",
        "verified_email": True,
    },
    "customer_locale": "de",
    "device_id": None,
    "discount_applications": [],
    "discount_codes": [],
    "duties_included": False,
    "estimated_taxes": False,
    "financial_status": "paid",
    "fulfillment_status": None,
    "fulfillments": [],
    "id": 11755494146422,
    "landing_site": None,
    "landing_site_ref": None,
    "line_items": [
        {
            "admin_graphql_api_id": "gid://shopify/LineItem/34952236401014",
            "attributed_staffs": [],
            "current_quantity": 1,
            "discount_allocations": [],
            "duties": [],
            "fulfillable_quantity": 1,
            "fulfillment_service": "manual",
            "fulfillment_status": None,
            "gift_card": False,
            "grams": 200,
            "id": 34952236401014,
            "name": "Testartikel Shopify",
            "price": "111.00",
            "price_set": {
                "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
                "shop_money": {"amount": "111.00", "currency_code": "CHF"},
            },
            "product_exists": True,
            "product_id": 15177760440694,
            "properties": [],
            "quantity": 1,
            "requires_shipping": True,
            "sales_line_item_group_id": None,
            "sku": "111",
            "tax_lines": [
                {
                    "channel_liable": False,
                    "price": "8.32",
                    "price_set": {
                        "presentment_money": {"amount": "8.32", "currency_code": "CHF"},
                        "shop_money": {"amount": "8.32", "currency_code": "CHF"},
                    },
                    "rate": 0.081,
                    "title": "MwSt",
                }
            ],
            "taxable": True,
            "title": "Testartikel Shopify",
            "total_discount": "0.00",
            "total_discount_set": {
                "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
                "shop_money": {"amount": "0.00", "currency_code": "CHF"},
            },
            "variant_id": 55607992746358,
            "variant_inventory_management": "shopify",
            "variant_title": None,
            "vendor": "Virima AG",
        }
    ],
    "location_id": None,
    "merchant_business_entity_id": "MTkxNTk5Mjc0MzU4",
    "merchant_of_record_app_id": None,
    "name": "#1009",
    "note": None,
    "note_attributes": [],
    "number": 9,
    "order_number": 1009,
    "original_total_additional_fees_set": None,
    "original_total_duties_set": None,
    "payment_gateway_names": ["manual"],
    "payment_terms": None,
    "po_number": None,
    "presentment_currency": "CHF",
    "processed_at": "2025-05-23T12:22:20+02:00",
    "reference": None,
    "referring_site": None,
    "refunds": [],
    "returns": [],
    "shipping_address": {
        "country": "Switzerland",
        "country_code": "CH",
        "province": None,
        "province_code": None,
    },
    "shipping_lines": [],
    "source_identifier": None,
    "source_name": "shopify_draft_order",
    "source_url": None,
    "subtotal_price": "111.00",
    "subtotal_price_set": {
        "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
        "shop_money": {"amount": "111.00", "currency_code": "CHF"},
    },
    "tags": "",
    "tax_exempt": False,
    "tax_lines": [
        {
            "channel_liable": False,
            "price": "8.32",
            "price_set": {
                "presentment_money": {"amount": "8.32", "currency_code": "CHF"},
                "shop_money": {"amount": "8.32", "currency_code": "CHF"},
            },
            "rate": 0.081,
            "title": "MwSt",
        }
    ],
    "taxes_included": True,
    "test": False,
    "token": "79aef01c77b1732006f31613d36f3342",
    "total_cash_rounding_payment_adjustment_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "total_cash_rounding_refund_adjustment_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "total_discounts": "0.00",
    "total_discounts_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "total_line_items_price": "111.00",
    "total_line_items_price_set": {
        "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
        "shop_money": {"amount": "111.00", "currency_code": "CHF"},
    },
    "total_outstanding": "0.00",
    "total_price": "111.00",
    "total_price_set": {
        "presentment_money": {"amount": "111.00", "currency_code": "CHF"},
        "shop_money": {"amount": "111.00", "currency_code": "CHF"},
    },
    "total_shipping_price_set": {
        "presentment_money": {"amount": "0.00", "currency_code": "CHF"},
        "shop_money": {"amount": "0.00", "currency_code": "CHF"},
    },
    "total_tax": "8.32",
    "total_tax_set": {
        "presentment_money": {"amount": "8.32", "currency_code": "CHF"},
        "shop_money": {"amount": "8.32", "currency_code": "CHF"},
    },
    "total_tip_received": "0.00",
    "total_weight": 200,
    "updated_at": "2025-05-23T12:22:21+02:00",
    "user_id": 130240610678,
}


def test_sync_sales_order():
    sync_sales_order(payload)
